name: flutterguard

packages:
  - packages/**
  - examples/**

command:
  bootstrap:
    usePubspecOverrides: true
  version:
    branch: main

scripts:
  analyze:
    run: melos exec -c 1 -- "dart analyze ."
  format:
    run: melos exec -- "dart format ."
  test:
    run: dart run melos exec -c 1 --scope="flutterguard_*" -- dart test
  test:core:
    run: dart run melos exec --scope="flutterguard_core" -- dart test
  test:dio:
    run: dart run melos exec --scope="flutterguard_dio" -- dart test
  test:cli:
    run: dart run melos exec --scope="flutterguard_cli" -- dart test
