name: flutterguard

packages:
  - packages/flutterguard_cli
  - examples/**

command:
  bootstrap:
    usePubspecOverrides: true
  version:
    branch: main

scripts:
  analyze:
    run: dart run melos exec -c 1 -- "dart analyze ."
  format:
    run: dart run melos exec -- "dart format ."
  test:
    run: dart run melos exec --scope="flutterguard_cli" -- dart test
  test:cli:
    run: dart run melos exec --scope="flutterguard_cli" -- dart test
