name: checkout_flow_example
description: Demo app showing FlutterGuard runtime integration.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutterguard_flutter:
    path: ../../packages/flutterguard_flutter
  flutterguard_dio:
    path: ../../packages/flutterguard_dio
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
